Repository PatoGuereque/Learn-to-Py, pull requests merged in 2021-05, with the labels that each got.

#14 fix - Refactor, fix and add connection between code logic and views
  .DS_Store
  Learn-to-py.xcodeproj/project.pbxproj
  Learn-to-py/.DS_Store
  Learn-to-py/Assets.xcassets/Images/Lapiz.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Lapiz.imageset/lapiz.png
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/CodeTemplate.swift
  Learn-to-py/EditIterable.swift
  Learn-to-py/EditSnippet.swift
  Learn-to-py/EditVariable.swift
  Learn-to-py/Enums.swift
  Learn-to-py/Logic.swift
  Learn-to-py/PopUpEditarIterable.swift
  Learn-to-py/PopUpEditarSeleccionCodigo.swift
  Learn-to-py/Variable.swift
  Learn-to-py/ViewControllerCicloFor.swift
  Learn-to-py/ViewControllerForLoop.swift
  Learn-to-py/fonts/.DS_Store
Labels: bug, enhancement

#18 Feature/py display, Variables Graphic Updates (Closes #16)
  Learn-to-py.xcodeproj/project.pbxproj
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/EditSnippet.swift
  Learn-to-py/Logic.swift
  Learn-to-py/ViewControllerForLoop.swift
  Learn-to-py/interpreter/CodeColor.swift
  Learn-to-py/interpreter/CodeSnippet.swift
  Learn-to-py/interpreter/CodeTemplate.swift
  Learn-to-py/interpreter/Enums.swift
  Learn-to-py/interpreter/Step.swift
  Learn-to-py/interpreter/Utils.swift
  Learn-to-py/interpreter/Variable.swift
  Learn-to-py/interpreter/snippets/IfElseSnippet.swift
  Learn-to-py/interpreter/snippets/PrintSnippet.swift
Labels: enhancement, view/component/class

#19 view/cuestionario fix
  .DS_Store
  Learn-to-py.xcodeproj/project.pbxproj
  Learn-to-py/Assets.xcassets/Images/Learn to Py logo.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Learn to Py logo.imageset/Learn to Py logo.png
  Learn-to-py/Assets.xcassets/Images/Pregunta 1.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Pregunta 1.imageset/Pregunta 1.png
  Learn-to-py/Assets.xcassets/Images/Pregunta 2.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Pregunta 2.imageset/Pregunta 2.png
  Learn-to-py/Assets.xcassets/Images/Pregunta 3.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Pregunta 3.imageset/Pregunta 3.png
  Learn-to-py/Assets.xcassets/Images/Pregunta 4.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Pregunta 4.imageset/Pregunta 4.png
  Learn-to-py/Assets.xcassets/Images/Pregunta 5.imageset/Contents.json
  Learn-to-py/Assets.xcassets/Images/Pregunta 5.imageset/Pregunta 5.png
  Learn-to-py/Base.lproj/LaunchScreen.storyboard
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/CodeColor.swift
  Learn-to-py/EditIterable.swift
  Learn-to-py/EditVariable.swift
  Learn-to-py/ExamResult.swift
  Learn-to-py/ExamViewController.swift
  Learn-to-py/Question.swift
  Learn-to-py/ResultsViewController.swift
  Learn-to-py/ViewControllerForLoop.swift
  Learn-to-py/interpreter/Utils.swift
Labels: bug

#30 Fix/ranges in for loop
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/EditIterable.swift
  Learn-to-py/EditVariable.swift
  Learn-to-py/ViewControllerForLoop.swift
  Learn-to-py/interpreter/Enums.swift
Labels: bug, enhancement

#31 Enhancement/code snippets
  Learn-to-py.xcodeproj/project.pbxproj
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/ViewController.swift
  Learn-to-py/ViewControllerLoop.swift
  Learn-to-py/interpreter/CodeSnippet.swift
  Learn-to-py/interpreter/CodeTemplate.swift
  Learn-to-py/interpreter/Enums.swift
  Learn-to-py/interpreter/snippets/IfElseSnippet.swift
  Learn-to-py/interpreter/snippets/PrintSnippet.swift
  Learn-to-py/interpreter/snippets/SumSnippet.swift
  Learn-to-py/interpreter/templates/ForLoopTemplate.swift
  Learn-to-py/interpreter/templates/WhileLoopTemplate.swift
Labels: enhancement

#33 Add constraints to loop view
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/ViewControllerLoop.swift
Labels: enhancement

#36 Add App Icon (Closes #34)
  .DS_Store
  Learn-to-py/.DS_Store
  Learn-to-py/Assets.xcassets/.DS_Store
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/.DS_Store
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/100.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/1024.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/114.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/120.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/128.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/144.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/152.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/16.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/167.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/172.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/180.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/196.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/20.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/216.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/256.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/29.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/32.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/40.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/48.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/50.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/512.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/55.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/57.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/58.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/60.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/64.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/72.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/76.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/80.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/87.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/88.png
  Learn-to-py/Assets.xcassets/AppIcon.appiconset/Contents.json
  Learn-to-py/Assets.xcassets/Images/.DS_Store
  Learn-to-py/Base.lproj/Main.storyboard
Labels: Prioridad Alta, enhancement

#38 Fix/constraints (Closes #21)
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/ExamViewController.swift
  Learn-to-py/ResultsViewController.swift
Labels: Prioridad Alta, enhancement

#39 Ya se randomiza el iterador al loadear el load y ya le cambie la view…
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/ViewControllerLoop.swift
Labels: enhancement

#40 Remove decimal point in exam results view to display correct answers as interger.
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/ResultsViewController.swift
Labels: bug

#41 Add keyboard hiding functionality on outside tap
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/ExamViewController.swift
  Learn-to-py/ViewController.swift
Labels: bug

#42 Add Python logo reference inside information section
  Learn-to-py/Base.lproj/Main.storyboard
Labels: enhancement

#44 fix - Resolve requested fixes.
  Learn-to-py/Base.lproj/Main.storyboard
  Learn-to-py/EditIterable.swift
  Learn-to-py/ExamViewController.swift
  Learn-to-py/ResultsViewController.swift
  Learn-to-py/ViewControllerLoop.swift
  Learn-to-py/interpreter/CodeTemplate.swift
  Learn-to-py/interpreter/snippets/AboveTenCounterSnippet.swift
  Learn-to-py/interpreter/snippets/IfElseSnippet.swift
  Learn-to-py/interpreter/templates/ForLoopTemplate.swift
  Learn-to-py/interpreter/templates/WhileLoopTemplate.swift
Labels: bug

#45 Fix keyboard popup resetting position and invalid step
  Learn-to-py/EditIterable.swift
  Learn-to-py/EditVariable.swift
  Learn-to-py/KeyboardViewPushController.swift
  Learn-to-py/ViewControllerLoop.swift
Labels: view/component/class
